on:
  push:
    branches: [main]
  pull_request:
    types: [opened, closed, reopened]
  issues:
    types: [opened, closed, reopened]
jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: yehuoshun/yehuoshun-notify@e2b1d4281b6ee5a22bfd866e86113d19b1ce06c6 # v1.2.0
        with:
          webhook: ${{ secrets.DINGTALK_WEBHOOK }}
